# Generated by Django 3.2.8 on 2021-10-14 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Титульник райдера')),
                ('description', models.TextField(verbose_name='Общее описание райдера')),
            ],
            options={
                'verbose_name': 'Райдер общий',
                'verbose_name_plural': 'Райдер общий',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Общее фото')),
                ('description', models.TextField(verbose_name='Общее описание коллектива')),
            ],
            options={
                'verbose_name': 'Коллектив',
                'verbose_name_plural': 'Коллектив',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=256, verbose_name='Цена от')),
                ('price_includes', models.TextField(verbose_name='В стоимость входит')),
                ('price_not_include', models.TextField(verbose_name='В стоимость не входит')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото на главной странице')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото участника')),
                ('about_me', models.CharField(max_length=1000, verbose_name='О себе')),
                ('comment', models.CharField(blank=True, max_length=1000, verbose_name='Комментарий (не обязательно к заполнению)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nevada_shop.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Райдер')),
                ('photo', models.FileField(upload_to='pdf/', verbose_name='PDF-файл')),
                ('about_me', models.TextField(verbose_name='Краткое описание')),
                ('comment', models.TextField(verbose_name='Полное описание')),
                ('main_rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nevada_shop.commonrider', verbose_name='Общий райдер')),
            ],
            options={
                'verbose_name': 'Райдер',
                'verbose_name_plural': 'Райдер',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Repertoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Композиция')),
                ('comment', models.CharField(blank=True, max_length=256, verbose_name='Комментарий (не обязательно к заполнению)')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nevada_shop.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Композиция',
                'verbose_name_plural': 'Список композиций',
                'ordering': ['pk'],
            },
        ),
    ]
