# Generated by Django 3.2.8 on 2022-12-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nevada_shop', '0002_auto_20211023_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonrider',
            options={'verbose_name': 'Райдер', 'verbose_name_plural': 'Райдер'},
        ),
        migrations.AddField(
            model_name='group',
            name='main_photo',
            field=models.ImageField(default='none', upload_to='photos/', verbose_name='Фото на главной странице'),
            preserve_default=False,
        ),
    ]
